"use strict";
exports.__esModule = true;
exports.REJECT = exports.INVENTORY = void 0;
var INVENTORY;
(function (INVENTORY) {
    INVENTORY[INVENTORY["ERROR"] = 0] = "ERROR";
    INVENTORY[INVENTORY["MSG_TX"] = 1] = "MSG_TX";
    INVENTORY[INVENTORY["MSG_BLOCK"] = 2] = "MSG_BLOCK";
    INVENTORY[INVENTORY["MSG_FILTERED_BLOCK"] = 3] = "MSG_FILTERED_BLOCK";
    INVENTORY[INVENTORY["MSG_WITNESS_TX"] = 1073741825] = "MSG_WITNESS_TX";
    INVENTORY[INVENTORY["MSG_WITNESS_BLOCK"] = 1073741826] = "MSG_WITNESS_BLOCK";
})(INVENTORY = exports.INVENTORY || (exports.INVENTORY = {}));
var REJECT;
(function (REJECT) {
    REJECT[REJECT["MALFORMED"] = 1] = "MALFORMED";
    REJECT[REJECT["INVALID"] = 16] = "INVALID";
    REJECT[REJECT["OBSOLETE"] = 17] = "OBSOLETE";
    REJECT[REJECT["DUPLICATE"] = 18] = "DUPLICATE";
    REJECT[REJECT["NONSTANDARD"] = 64] = "NONSTANDARD";
    REJECT[REJECT["DUST"] = 65] = "DUST";
    REJECT[REJECT["INSUFFICIENTFEE"] = 66] = "INSUFFICIENTFEE";
    REJECT[REJECT["CHECKPOINT"] = 67] = "CHECKPOINT";
})(REJECT = exports.REJECT || (exports.REJECT = {}));
